site_name: 404黄台软件大全
site_author: 404黄台
site_description: 全球404黄台聚合平台，提供实时收听、历史回放、智能推荐服务，涵盖音乐、新闻、有声书等全品类音频内容，支持多终端无缝切换。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
